on:
  push:
    branches: ["main"]
jobs:
  build:
    name: Build nugget package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
# dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/NAMESPACE/index.json"

# dotnet pack --configuration Release

# dotnet nuget push "bin/Release/PROJECT_NAME.1.0.0.nupkg"  --api-key YOUR_GITHUB_PAT --source "github"
