name: "Deploy to NuGet"

on:
  push:
    # branches: ["main"]
    tags:
    - 'v*'
env:
  PROJECT_PATH: 'RPNCalculator/RPNCalculator.csproj'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: 'https://nuget.pkg.github.com/shinso-raven/index.json'

jobs:
  build:
    name: Build nugget package
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8 

    - name: 'Restore packages'
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: 'Build project'
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release

    - name: 'Get Version'
      id: version
      uses: battila7/get-version-action@v2

    - name: 'Pack project'
      run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release --include-symbols -p:PackageVersion=${{ steps.version.outputs.version-without-v }} 
      # authenticate
    - name: 'authenticate source'
      run: dotnet nuget add source --username shinso-raven --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/shinso-raven/index.json"

#push
    - name: 'Push package'
      run: dotnet nuget push /RPNCalculator/bin/Release/RPNCalculator.${{ steps.version.outputs.version-without-v }}.nupkg -k ${{ secrets.NUGET_AUTH_TOKEN }} -s ${{ env.NUGET_SOURCE_URL }}


      # run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\*.nupkg  --api-key YOUR_GITHUB_PAT --source "github"

      # run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\*.nupkg -k ${{ secrets.NUGET_AUTH_TOKEN }} -s ${{ env.NUGET_SOURCE_URL }}



# dotnet pack --configuration Release

# dotnet nuget push "bin/Release/PROJECT_NAME.1.0.0.nupkg"  --api-key YOUR_GITHUB_PAT --source "github"



